// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh0wdqxuP6Y16ZDKLFicKqdbw33SgzPwA',
    appId: '1:306288778385:android:7489c3fcbb072f01f23330',
    messagingSenderId: '306288778385',
    projectId: 'let-find-13a58',
    databaseURL: 'https://let-find-13a58-default-rtdb.firebaseio.com',
    storageBucket: 'let-find-13a58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn_YxEZWQQMeD-uc28BdHlkfLNrF4UgLE',
    appId: '1:306288778385:ios:5a92941d56864bd5f23330',
    messagingSenderId: '306288778385',
    projectId: 'let-find-13a58',
    databaseURL: 'https://let-find-13a58-default-rtdb.firebaseio.com',
    storageBucket: 'let-find-13a58.appspot.com',
    iosClientId: '306288778385-jq0dfu7oqfnvhbdpd7b9lsg2153ojrjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.smokeDetector',
  );
}
